
version: 2

sources:
  - name: clone_small_sample_data
    description: "Sample Data"
    database: snowflake_sample_data
    schema: TPCDS_SF10TCL
    tables:
      - name: store_sales
        description: "Details about sales in the store"

models:
  - name: clone_small_sample_data__store_sales
    description: "Starter"
    columns:
        - name: SS_ITEM_SK
          tests:
            - not_null

